name: acrhitecture_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  build_runner: ^2.1.1
  cupertino_icons: ^1.0.2
  #localization
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  #mobx
  flutter_mobx: ^2.0.2
  mobx: ^2.0.4
  mobx_codegen: any
  #provider
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
